### PR TITLE
Master

### PR DESCRIPTION
**Pull request by nwf**

### CODE REVIEW

**Comment by mibodhi** [comment]
nwf,

I'll merge the pull request in the next couple weeks. And will rebase everything to the latest u-boot at the same time. Sorry for taking so long to act on this pull request:)

-bodhi

**Comment by mibodhi** [comment]
I'm having problem pulling the changes (some non existent email or repo). Sorry about this, but I'll close the pull request and will merge the changes manually.

**Comment by nwf** [comment]
I don't mean to be mean, but, would you consider leaving this open until the bits land in your tree? :)

**Comment by mibodhi** [comment]
Hi Nathan!

Sure :) it's my fault for being late on this. But your repo, that the original pull request was from, has been deleted? Could you check that, I tried to reopen the pull request just now but was not successful. Because the repo was deleted, I thought you're no longer interested in the pull request! If you'd like to redo the pull request, I'd be happy to try again.

**Comment by nwf** [comment]
Sorry, I think I have deleted the repository even locally without thinking.  I am still interested in the changes, but since I gave up on building uboot by hand and just do so through OpenWRT, I merged the changes myself in my tree via https://github.com/nwf/openwrt/commit/4560423ca313a7ede0a8d7543f3e97be9c2280e7 .

I've reconstructed the repo at #4.  The missing patch ("Modernize...") got clobbered in the interim and can be dropped.

**Pull request closed without merging**
